// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSimpleRechargeInfo = "simple_recharge_info"

// SimpleRechargeInfo mapped from table <simple_recharge_info>
type SimpleRechargeInfo struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                           // ID
	TradeNumber string `gorm:"column:trade_number;not null;type:varchar(255);comment:Delivery service order number" json:"trade_number"` // Delivery service order number
	Count       int32  `gorm:"column:count;not null;comment:Quantity to be shipped" json:"count"`                      // Quantity to be shipped
}

// TableName SimpleRechargeInfo's table name
func (*SimpleRechargeInfo) TableName() string {
	return TableNameSimpleRechargeInfo
}
